/* Copyright 2024-2026 Esri
 *
 * Licensed under the Apache License Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// import { ARCGIS_PROTAL_ROOT } from "@constants/index";
import { delay } from '@utils/snippets/delay';

type AddTilePackageItemParams = {
    /**
     * The URL that will be used to download the tile package data. This URL should point to the location where the tile package file is hosted and can be accessed for download.
     */
    dataUrl: string;
    /**
     * The title of the tile package item to be added.
     */
    title: string;
    /**
     * Summary text for the tile package item.
     */
    snippet?: string;
    /**
     * Authentication token.
     */
    token: string;
    /**
     * The username of the ArcGIS account where the tile package item will be added.
     */
    username: string;
    /**
     * The root URL of the ArcGIS Portal. If not provided, it will default to'https://www.arcgis.com'.
     */
    portalRoot?: string;
};

type AddItemResponse = {
    /**
     * Indicates if the operation was successful
     */
    success: boolean;
    /**
     * Item ID of the newly created item in ArcGIS Portal.
     */
    id: string;
    /**
     * Name of the folder where the item is added.
     */
    folder?: string;
};

/**
 * Adds a tile package item to the specified user's content in ArcGIS Portal.
 * The item is created asynchronously using a remote data URL pointing to the hosted tile package file.
 *
 * @param {AddTilePackageItemParams} params - The parameters for adding the tile package item.
 * @param {string} params.dataUrl - The URL where the tile package file is hosted for download.
 * @param {string} params.title - The title of the tile package item.
 * @param {string} [params.snippet] - Summary text for the item. Defaults to 'Tile package generated by Wayport'.
 * @param {string} params.token - Authentication token for the ArcGIS Portal API.
 * @param {string} params.username - The ArcGIS account username to add the item under.
 * @param {string} [params.portalRoot='https://www.arcgis.com'] - The root URL of the ArcGIS Portal.
 * @returns {Promise<AddItemResponse>} The response containing the new item's ID and success status.
 * @throws {Error} If `dataUrl`, `token`, or `username` is missing.
 * @throws {Error} If the HTTP request fails or the server returns an error.
 *
 * @see https://developers.arcgis.com/rest/users-groups-and-items/add-item/#description
 */
export const addTilePackageItem = async ({
    title,
    dataUrl,
    snippet,
    token,
    username,
    portalRoot = 'https://www.arcgis.com',
}: AddTilePackageItemParams): Promise<AddItemResponse> => {
    if (!dataUrl) {
        throw new Error('dataUrl is required to add tile package item');
    }

    if (!token) {
        throw new Error('token is required to add tile package item');
    }

    if (!username) {
        throw new Error('username is required to add tile package item');
    }

    const requestUrl = `${portalRoot}/sharing/rest/content/users/${username}/addItem`;

    const params = new URLSearchParams({
        type: 'Tile Package',
        extension: 'tpkx',
        typeKeywords: 'tpkx',
        title: title || `Wayback Tile Package - ${new Date().getTime()}`,
        snippet: snippet || 'Tile package generated by Wayport',
        dataUrl,
        token,
        f: 'json',
        async: 'true',
    });

    const res = await fetch(requestUrl, {
        method: 'POST',
        body: params,
    });

    if (!res.ok) {
        throw new Error(
            `Failed to add tile package item. Status: ${res.status}}`
        );
    }

    const data = await res.json();

    if (data?.error) {
        throw data.error;
    }

    if (!data?.success || !data?.id) {
        throw new Error(
            'Failed to add tile package item. Invalid response from server.'
        );
    }

    return data as AddItemResponse;
};

/**
 * Checks the processing status of an item in ArcGIS Portal.
 */
type CheckItemProcessingStatusParams = {
    /**
     * The ID of the item to check the processing status for.
     */
    itemId: string;
    /**
     * The username of the ArcGIS account that owns the item being checked.
     */
    userId: string;
    /**
     * Authentication token for the ArcGIS Portal API.
     */
    token: string;
    /**
     * The root URL of the ArcGIS Portal. If not provided, it will default to'https://www.arcgis.com'.
     */
    portalRoot?: string;
};

type CheckItemProcessingStatusResponse = {
    /**
     * The processing status of the item. Possible values include 'completed', 'processing', 'error', etc.
     */
    status: 'partial' | 'processing' | 'failed' | 'completed';
    /**
     * Item ID of the item being checked.
     */
    itemId: string;
};

/**
 * Checks the processing status of an item in ArcGIS Portal.
 * Polls the item's status endpoint to determine whether asynchronous processing has completed.
 *
 * @param {CheckItemProcessingStatusParams} params - The parameters for checking item status.
 * @param {string} params.itemId - The ID of the item to check.
 * @param {string} params.token - Authentication token for the ArcGIS Portal API.
 * @param {string} [params.portalRoot='https://www.arcgis.com'] - The root URL of the ArcGIS Portal.
 *
 * @returns {Promise<CheckItemProcessingStatusResponse>} The processing status of the item.
 *
 * @throws {Error} If `itemId` or `token` is missing.
 * @throws {Error} If the HTTP request fails or the server returns an error.
 * @see https://developers.arcgis.com/rest/users-groups-and-items/status/
 */
export const checkItemProcessingStatus = async ({
    itemId,
    userId,
    token,
    portalRoot = 'https://www.arcgis.com',
}: CheckItemProcessingStatusParams): Promise<CheckItemProcessingStatusResponse> => {
    if (!itemId) {
        throw new Error('itemId is required to check item processing status');
    }
    if (!token) {
        throw new Error('token is required to check item processing status');
    }

    const requestUrl = `${portalRoot}/sharing/rest/content/users/${userId}/items/${itemId}/status?token=${token}&f=json`;

    const res = await fetch(requestUrl);

    if (!res.ok) {
        throw new Error(
            `Failed to check item processing status. Status: ${res.status}}`
        );
    }

    const data = await res.json();

    if (data?.error) {
        throw data.error;
    }

    if (!data?.status) {
        throw new Error(
            'Failed to check item processing status. Invalid response from server.'
        );
    }

    return data as CheckItemProcessingStatusResponse;
};

// /**
//  * Creates a tile package item in ArcGIS Portal and polls until server-side processing is complete.
//  * Combines {@link addTilePackageItem} and {@link checkItemProcessingStatus} into a single workflow:
//  * first adds the item, then polls the processing status every 10 seconds until it reaches
//  * `'completed'` or `'failed'`. If processing fails or doesn't complete within 15 minutes, an error is thrown.
//  *
//  * @param {AddTilePackageItemParams} params - The parameters for adding the tile package item.
//  * @returns {Promise<string>} The item ID of the successfully processed tile package.
//  * @throws {Error} If the item fails to be added or if server-side processing fails.
//  */
// export const createTilePackageItemAndWaitForCompletion = async (
//     params: AddTilePackageItemParams
// ): Promise<string> => {
//     const { token, portalRoot } = params;

//     // Step 1: Add tile package item
//     const addItemResponse = await addTilePackageItem(params);
//     const itemId = addItemResponse.id;

//     // Step 2: Poll item processing status until it's completed
//     const maxWaitTime = 15 * 60 * 1000; // 15 minutes
//     const startTime = Date.now();
//     let processingStatusResponse: CheckItemProcessingStatusResponse;

//     while (true) {
//         processingStatusResponse = await checkItemProcessingStatus({
//             itemId,
//             token,
//             portalRoot,
//             userId: params.username,
//         });

//         if (processingStatusResponse.status === 'completed') {
//             break;
//         } else if (processingStatusResponse.status === 'failed') {
//             throw new Error(`Item processing failed for item ID: ${itemId}`);
//         }

//         if (Date.now() - startTime >= maxWaitTime) {
//             throw new Error(
//                 `Item processing timed out after 15 minutes for item ID: ${itemId}`
//             );
//         }

//         await delay(10000); // Wait for 10 seconds before polling again
//     }

//     return itemId;
// };
